// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiIqWgrSTAmeuvT1n2DvrE61fzqhInQik',
    appId: '1:805440285084:web:1c6dd1c86b4465279c4059',
    messagingSenderId: '805440285084',
    projectId: 'ecommerceapps-55082',
    authDomain: 'ecommerceapps-55082.firebaseapp.com',
    storageBucket: 'ecommerceapps-55082.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7q3vJbNdjj50lN18cbLUqvHmo5yvfM6A',
    appId: '1:805440285084:android:65ce8a9f4cd7d2db9c4059',
    messagingSenderId: '805440285084',
    projectId: 'ecommerceapps-55082',
    storageBucket: 'ecommerceapps-55082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThijaV3RwjR4LEIa5TBoFqLGbeRR1DLA',
    appId: '1:805440285084:ios:b80d65557c37ba239c4059',
    messagingSenderId: '805440285084',
    projectId: 'ecommerceapps-55082',
    storageBucket: 'ecommerceapps-55082.firebasestorage.app',
    androidClientId: '805440285084-flhf6hbk1kqmem8arjtlbs5hqdugm01v.apps.googleusercontent.com',
    iosClientId: '805440285084-5d66k4iommrqjtrsldua1sb8fren4b35.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo2Fa4EvYhCEJTX0hR68Xo92W76-utx-k',
    appId: '1:914258883270:web:ab8b4b4c0c24208fb79dc7',
    messagingSenderId: '914258883270',
    projectId: 'ecommerceapp-833f8',
    authDomain: 'ecommerceapp-833f8.firebaseapp.com',
    storageBucket: 'ecommerceapp-833f8.firebasestorage.app',
  );

}